name: TRICK A4IF WORKER BOT

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # প্রতি ৫ ঘণ্টা পর পর অটোমেটিক রান হবে

jobs:
  run-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
      - name: Fetch Code from Master Repo
        uses: actions/checkout@v4
        with:
          repository: arifyoutubeshorts-max/Trick-A4IF-Master
          token: ${{ secrets.MASTER_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Initialize Dependencies
        run: |
          npm init -y
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth telegraf fs-extra node-fetch@2

      # এখানে CLIENT_ID দিয়ে মাস্টার/ওয়ার্কার ডিটেক্ট হবে
      - name: Ignite TRICK A4IF Engine
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: node engine.obfuscated.js
